# Generated by Django 3.1 on 2022-02-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0003_auto_20220201_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('-quantity',)},
        ),
    ]
